version: "3.4"
services:
  app:
    tty: true
    stdin_open: true
    container_name: http2s
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/rails
    ports:
      - 3000:3000
